let handler = async (m, { conn, usedPrefix, text }) => {
 
    m.reply(`memanggil dukun...`)
    await sleep(1000) 
    m.reply("mendapatkan informasi khodam..") 
    await sleep(1000) 
    m.reply(`khodam kamu adalah : ${await pickRandom(khodam)}`) 
      
    };
    handler.help = ["cekkhodam"];
    handler.tags = ["rpg"];
    handler.command = /^(cekkhodam)/i;
    handler.register = true;
    handler.group = true;
    export default handler;
    
    function pickRandom(list) {
      return list[Math.floor(list.length * Math.random())]
    }
    
    const khodam = [
      "Singa",
      "kosoong atau tidak ada",
      "Harimau",
      "Elang",
      "Serigala",
      "Naga",
      "Gajah",
      "Kuda",
      "Macan Tutul",
      "Kerbau",
      "Burung Hantu",
      "Burung Rajawali",
      "Ikan Hiu",
      "Lumba-Lumba",
      "Ular",
      "Kura-Kura",
      "Tupai",
      "Paus",
      "Kelelawar",
      "Kijang",
      "Banteng",
      "Rusa",
      "Anjing",
      "Kucing",
      "Buaya",
      "Kambing",
      "Kuda Nil",
      "Bebek",
      "Angsa",
      "Ayam",
      "Merpati",
      "Burung Beo",
      "Burung Kenari",
      "Burung Kakatua",
      "Bunglon",
      "Cicak",
      "Kodok",
      "Katak",
      "Tikus",
      "Landak",
      "Kanguru",
      "Koala",
      "Panda",
      "Beruang",
      "Rubah",
      "Lynx",
      "Leopard",
      "Jaguar",
      "Cheetah",
      "Badak",
      "Zebra",
      "Antelop",
      "Unta",
      "Alpaka",
      "Llama",
      "Serigala Abu-abu",
      "Serigala Merah",
      "Serigala Putih",
      "Lynx",
      "Harimau Putih",
      "Harimau Siberia",
      "Harimau Sumatra",
      "Gorila",
      "Orangutan",
      "Simpanse",
      "Monyet",
      "Babun",
      "Lemur",
      "Iguana",
      "Komodo",
      "Salamander",
      "Belut",
      "Sotong",
      "Gurita",
      "Kepiting",
      "Lobster",
      "Udang",
      "Kupu-kupu",
      "Lebah",
      "Tawon",
      "Kumbang",
      "Belalang",
      "Jangkrik",
      "Semut",
      "Kecoak",
      "Laba-laba",
      "Kalajengking",
      "Serangga Tongkat",
      "Naga Laut",
      "Kuda Laut",
      "Duyung",
      "Putri Duyung",
      "Burung Kolibri",
      "Burung Hantu Salju",
      "Burung Puyuh",
      "Burung Gagak",
      "Burung Pelikan",
      "Burung Albatros",
      "Burung Flamingo",
      "Burung Hering",
      "Burung Camar",
      "Burung Pinguin",
        "Cincin",
        "Batu Akik",
        "Keris",
        "Tongkat",
        "Pusaka",
        "Patung",
        "Mustika",
        "Tasbih",
        "Kalung",
        "Gelang",
        "Permata",
        "Pedang",
        "Mata Uang",
        "Wesi Kuning",
        "Serat Tali",
        "Belati",
        "Cundrik",
        "Selendang",
        "Jarum",
        "Tombak",
        "Kerikil",
        "Kendi",
        "Kain Kafan",
        "Topi",
        "Payung",
        "Sandal",
        "Kacamata",
        "Sabuk",
        "Sarung",
        "Tali Ikat Pinggang",
        "Surat",
        "Kunci",
        "Lilin",
        "Peniti",
        "Sisir",
        "Cermin",
        "Kendi Air",
        "Piring",
        "Gelas",
        "Mangkuk",
        "Sendok",
        "Sapu",
        "Gayung",
        "Tikar",
        "Bantal",
        "Guci",
        "Lentera",
        "Lampu",
        "Buku",
        "Pena",
        "Dupa",
        "Asbak",
        "Cangkir",
        "Gantungan Kunci",
        "Kalender",
        "Sepeda",
        "Lukisan",
        "Batu Kerikil",
        "Batu Kali",
        "Kipas",
        "Peci",
        "Sorban",
        "Rokok",
        "Topeng",
        "Gamelan",
        "Angklung",
        "Suling",
        "Wayang", 
        "Sepatu",
        "Jam Tangan",
        "Kosong atau tidak adaa",
        "landak sawah",
    "naga hytam",
    "Kuru kuru",
    "kak gem jir", 
    "cicak berenang",
    "tuyul mulet", 
    "serigala botak", 
    "kodok tebu", 
    "ayam kaki 6", 
    "kuntibapa", 
    "harimau ompong", 
    "kuda kudaan", 
    "gajah Mada", 
    "silit wangi", 
    ]
    
    